#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

DESTDIR = Release
CONFIG += release

DEFINES += RASPBERRY
LIBS += -LE:\Work\LibrariesCPlusPlus\boost_1_58_0_ARM7\stage\lib -lboost_system -lboost_thread
INCLUDEPATH += E:\Work\LibrariesCPlusPlus\boost_1_58_0_ARM7
QMAKE_CFLAGS += -std=c++14
QMAKE_CXXFLAGS += -std=c++14
COMMONFLAGS += 
QMAKE_LFLAGS += 
