#ifndef _E_MESSAGE_ID_H_

#define _E_MESSAGE_ID_H_

#include "../Defines/CommonDefines.hpp"

typedef enum _EMessageId : u8
{
    EMessageId_Unknown                                                      = 0,
    EMessageId_LogInd                                                       = 1,
    EMessageId_FaultInd                                                     = 2,
    EMessageId_PollingRequest                                               = 3,
    EMessageId_PollingResponse                                              = 4,
    EMessageId_ResetUnitRequest                                             = 5,
    EMessageId_ResetUnitResponse                                            = 6,
    EMessageId_SampleCarrierDataInd                                         = 7,
    EMessageId_HeaterTemperatureInd                                         = 8,
    EMessageId_ReferenceTemperatureInd                                      = 9,
    EMessageId_ControllerDataInd                                            = 10,
    EMessageId_SetHeaterPowerRequest                                        = 11,
    EMessageId_SetHeaterPowerResponse                                       = 12,
    EMessageId_CallibreADS1248Request                                       = 13,
    EMessageId_CallibreADS1248Response                                      = 14,
    EMessageId_SetChannelGainADS1248Request                                 = 15,
    EMessageId_SetChannelGainADS1248Response                                = 16,
    EMessageId_SetChannelSamplingSpeedADS1248Request                        = 17,
    EMessageId_SetChannelSamplingSpeedADS1248Response                       = 18,
    EMessageId_StartRegisteringDataRequest                                  = 19,
    EMessageId_StartRegisteringDataResponse                                 = 20,
    EMessageId_StopRegisteringDataRequest                                   = 21,
    EMessageId_StopRegisteringDataResponse                                  = 22,
    EMessageId_SetNewDeviceModeADS1248Request                               = 23,
    EMessageId_SetNewDeviceModeADS1248Response                              = 24,
    EMessageId_SetNewDeviceModeLMP90100ControlSystemRequest                 = 25,
    EMessageId_SetNewDeviceModeLMP90100ControlSystemResponse                = 26,
    EMessageId_SetNewDeviceModeLMP90100SignalsMeasurementRequest            = 27,
    EMessageId_SetNewDeviceModeLMP90100SignalsMeasurementResponse           = 28,
    EMessageId_SetControlSystemTypeRequest                                  = 29,
    EMessageId_SetControlSystemTypeResponse                                 = 30,
    EMessageId_SetControllerTunesRequest                                    = 31,
    EMessageId_SetControllerTunesResponse                                   = 32,
    EMessageId_SetProcessModelParametersRequest                             = 33,
    EMessageId_SetProcessModelParametersResponse                            = 34,
    EMessageId_SetControllingAlgorithmExecutionPeriodRequest                = 35,
    EMessageId_SetControllingAlgorithmExecutionPeriodResponse               = 36,
    EMessageId_RegisterNewSegmentToProgramRequest                           = 37,
    EMessageId_RegisterNewSegmentToProgramResponse                          = 38,
    EMessageId_DeregisterSegmentFromProgramRequest                          = 39,
    EMessageId_DeregisterSegmentFromProgramResponse                         = 40,
    EMessageId_StartSegmentProgramRequest                                   = 41,
    EMessageId_StartSegmentProgramResponse                                  = 42,
    EMessageId_StopSegmentProgramRequest                                    = 43,
    EMessageId_StopSegmentProgramResponse                                   = 44,
    EMessageId_SegmentStartedInd                                            = 45,
    EMessageId_SegmentsProgramDoneInd                                       = 46,
    EMessageId_StartReferenceTemperatureStabilizationRequest                = 47,
    EMessageId_StartReferenceTemperatureStabilizationResponse               = 48,
    EMessageId_StopReferenceTemperatureStabilizationRequest                 = 49,
    EMessageId_StopReferenceTemperatureStabilizationResponse                = 50,
    EMessageId_SetRTDPolynomialCoefficientsRequest                          = 51,
    EMessageId_SetRTDPolynomialCoefficientsResponse                         = 52,
    EMessageId_UnitReadyInd                                                 = 53,
    EMessageId_SetHeaterTemperatureInFeedbackModeRequest                    = 54,
    EMessageId_SetHeaterTemperatureInFeedbackModeResponse                   = 55,
	EMessageId_SetMaximumAllowedTemperatureRequest							= 56,
	EMessageId_SetMaximumAllowedTemperatureResponse							= 57,
    EMessageId_UnexpectedMasterMessageInd                                   = 99
} EMessageId;

#endif
